name: Runner Test 3

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Runner Information
        shell: pwsh
        run: |
          hostname
          whoami
          git --version
          dotnet --info

      - name: Build Solution
        shell: pwsh
        run: |
          dotnet build